import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap" rel="stylesheet" />
      </Head>
      <main className={styles.main}>
        <Link className={styles.link} href='/useEffectOne'>useEffectOne</Link>
        <Link className={styles.link} href='/useEffectTwo'>useEffectTwo</Link>
        <Link className={styles.link} href='/useEffectThree'>useEffectThree</Link>
        <Link className={styles.link} href='/carouselPage'>Carousel Page</Link>
      </main>
    </>
  )
}
